### PR TITLE
Search results refinement

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@saeedmb8 please review 

The pagination is working fine however the positioning of the headings is floating about.

screen shot 2017-08-31 at 2 52 49 pm

**Comment by Mitso** [comment]
:cake:  with @saeedmb8 changes.

**Comment by Mitso** [comment]
@saeedmb8 I think adding the top message of banner explains what the site is about. Its a CTA without it the banner does not make sense.

It makes sense to have a CTA along the search above the fold.

screen shot 2017-09-01 at 11 47 32 am
screen shot 2017-09-01 at 11 47 00 am

**Comment by smarzban** [comment]
👍

**Pull request merged**
