### PR TITLE
Udate article styles

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by nathanbegbie** [comment]
@Mitso do you have screenshots to show the difference that this makes? I'm happy with the code.

**Comment by Mitso** [comment]
@nathanbegbie please review 

screen shot 2017-09-14 at 3 37 48 pm
screen shot 2017-09-14 at 3 38 06 pm

**Comment by Mitso** [comment]
screen shot 2017-09-14 at 3 39 30 pm

**Comment by nathanbegbie** [comment]
:cake: :+1:

**Pull request merged**
